global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'blackrock-api'
    static_configs:
      - targets: ['blackrock-retirement-api:5477']
    metrics_path: '/actuator/prometheus'
